name: publish

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: 21
      #          cache: 'gradle'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build files
        run: ./gradlew build

      - name: read info
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './gradle.properties'
          properties: 'archives_base_name mod_version minecraft_version minecraft_version_upper minecraft_version_name'

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-featured: true
          modrinth-unfeature-mode: intersection

          modrinth-token: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}

          curseforge-token: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

          name: '${{ steps.properties.outputs.archives_base_name }}-${{ steps.properties.outputs.mod_version }}+${{ steps.properties.outputs.minecraft_version_name }}'
          version: '${{ steps.properties.outputs.mod_version }}+${{ steps.properties.outputs.minecraft_version_name }}'


          version-type: release

          changelog-file: CHANGELOG.md

          game-versions: |
            >=${{ steps.properties.outputs.minecraft_version }} < ${{ steps.properties.outputs.minecraft_version_upper }}

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail